### Project Aim:
#### "Predicting iPhone Purchase Decisions Using Naïve Bayes Classification"

In [1]:
# import liberaries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
dataset = pd.read_csv('iphone_purchase_records.csv')
dataset.head(5)

Age  Salary  Purchase Iphone
0   19   19000                0
1   35   20000                0
2   26   43000                0
3   27   57000                0
4   19   76000                0

In [4]:
x= dataset.iloc[:,:-1]
y= dataset['Purchase Iphone']

In [31]:
# now splitting of data into training and testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, random_state=45)

In [32]:
# apply Naive Bayes Classifier

In [33]:
from sklearn.naive_bayes import GaussianNB
classifier =  GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB()

In [34]:
y_pred = classifier.predict(x_test)
y_pred

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [35]:
# Evaluating the performance of model
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score
print(confusion_matrix(y_test,y_pred))

[[60  2]
 [ 6 32]]


In [36]:
print(accuracy_score(y_test,y_pred))

0.92


In [37]:
# precision = tp/(tp+fp)
print(precision_score(y_test,y_pred))

0.9411764705882353


In [38]:
# classification report
from  sklearn.metrics import classification_report
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.91      0.97      0.94        62\n           1       0.94      0.84      0.89        38\n\n    accuracy                           0.92       100\n   macro avg       0.93      0.90      0.91       100\nweighted avg       0.92      0.92      0.92       100\n'

In [47]:
# save the model

import joblib
joblib.dump(classifier, 'Naive_bayes.sav')


['Naive_bayes.sav']

In [48]:
# loading the model

import joblib
model = joblib.load('Naive_bayes.sav')

In [46]:
model.predict(x_test)

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)